# word embedding technique using embedding layer in keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'Understand the meaning of words',
     'Your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'Your videos are good']

Convert these sentences to one hot

In [4]:
vec_size=10000 # dict size

In [5]:
onehot_repr=[one_hot(words,vec_size) for words in sent]

In [6]:
onehot_repr

[[4262, 6303, 3993, 7825],
 [4262, 6303, 3993, 8858],
 [4262, 9034, 3993, 2833],
 [7465, 2183, 8742, 3117, 4675],
 [7465, 2183, 8742, 3117, 5829],
 [2023, 4262, 6381, 3993, 1935],
 [6538, 7051, 9001, 3117]]

word embedding representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
sent_size=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_size)
print(embedded_docs)

[[   0    0    0    0 4262 6303 3993 7825]
 [   0    0    0    0 4262 6303 3993 8858]
 [   0    0    0    0 4262 9034 3993 2833]
 [   0    0    0 7465 2183 8742 3117 4675]
 [   0    0    0 7465 2183 8742 3117 5829]
 [   0    0    0 2023 4262 6381 3993 1935]
 [   0    0    0    0 6538 7051 9001 3117]]


In [14]:
dim=10 #feature size

In [20]:
from keras.layers import Dense
from keras.layers import Flatten

In [38]:
model=Sequential()
model.add(Embedding(vec_size,dim,input_length=sent_size))
model.compile('adam','mse')

In [39]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [41]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 47ms/step


array([[[-0.04244603,  0.02808179, -0.03215821,  0.0181619 ,
          0.00495571,  0.00449451,  0.04408408, -0.04765656,
          0.01552482, -0.04535417],
        [-0.04244603,  0.02808179, -0.03215821,  0.0181619 ,
          0.00495571,  0.00449451,  0.04408408, -0.04765656,
          0.01552482, -0.04535417],
        [-0.04244603,  0.02808179, -0.03215821,  0.0181619 ,
          0.00495571,  0.00449451,  0.04408408, -0.04765656,
          0.01552482, -0.04535417],
        [-0.04244603,  0.02808179, -0.03215821,  0.0181619 ,
          0.00495571,  0.00449451,  0.04408408, -0.04765656,
          0.01552482, -0.04535417],
        [-0.01634897, -0.01353902,  0.00491099,  0.02974561,
         -0.00467606,  0.00569352,  0.039627  , -0.00591388,
          0.03356021, -0.03097175],
        [ 0.02889055, -0.00752007,  0.02154273,  0.03832544,
         -0.04305425, -0.01359558, -0.00732783,  0.04698977,
         -0.04451392,  0.04063607],
        [-0.01153485,  0.01421472, -0.01946034, -0.0

In [17]:
onehot_repr[0]

[4262, 6303, 3993, 7825]

In [24]:
model.predict(embedded_docs)[0]

1/1 [==============================] - 0s 18ms/step


array([0.49304911], dtype=float32)